# Site settings
author: Lesly Jean-Baptiste
title: Why  I decide to learn programming
header-img: img/home-bg.png
email: lesjba56@yahoo.com
copyright_name: Lesly Jean-Baptiste
description: > # this means to ignore newlines until "baseurl:"
  Why programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lesjba21

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
